print('EEEEEEE U     U L       EEEEEEE RRRRRR')
print('E       U     U L       E       R     R')
print('EEEEEEE U     U L       EEEEEEE RRRRRRR')
print('E       U     U L       E       R    R')
print('EEEEEEE UUUUUUU LLLLLLL EEEEEEE R     R')